config/routes.rb
OrgelSpenderNetzwerk::Application.routes.draw do
  
  get "blood/new"
  get "blood/index"
  get "blood/update"
  get "blood/show"

  get "hospitals/index"
  devise_for :hospitals
  resources :hospitals

  resources :hospitals do
    collection do
      resources :blood
    end
  end

  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  root  'static_pages#home'

end

app/models/blood.rb
class Blood < ActiveRecord::Base
	belongs_to :hospitals
	attr_accessible :donor, :type, :reciever
end

app/models/hospital.rb
class Hospital < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :hospital_name, :hospital_id, :address, :city, :state, :district, :zip, :phone

  validates_presence_of :hospital_name, :hospital_id, :address, :city, :state, :district, :zip, :phone
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:hospital_name, :hospital_id, :address, :city, :district, :state, :zip, :phone]
    devise_parameter_sanitizer.for(:account_update) << :name
  end

end

app/controllers/blood_controller.rb
class BloodController < ApplicationController
  def new
  end

  def index
  end

  def update
  end

  def show
  end
end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController
  def new
  end

  def show
    @blood = Blood.new
  end

  def update
  end

  def edit
  end

  def index
    @hospitals = Hospital.paginate(page: params[:page])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
  
  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	# Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Thunderbolt"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end

end

app/helpers/blood_helper.rb
module BloodHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
	def gravatar_for(hospital, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(hospital.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: hospital.hospital_name, class: "gravatar")
  	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/blood/index.html.erb
<h1>Blood#index</h1>
<p>Find me in app/views/blood/index.html.erb</p>

app/views/blood/new.html.erb
<h1>Blood#new</h1>
<p>Find me in app/views/blood/new.html.erb</p>

app/views/blood/show.html.erb
<h1>Blood#show</h1>
<p>Find me in app/views/blood/show.html.erb</p>

app/views/blood/update.html.erb
<h1>Blood#update</h1>
<p>Find me in app/views/blood/update.html.erb</p>

app/views/hospitals/edit.html.erb
<h1>Hospitals#edit</h1>
<p>Find me in app/views/hospitals/edit.html.erb</p>

app/views/hospitals/index.html.erb
<% provide(:title, 'All hospitals') %>
<h1>All hospitals</h1>

<%= will_paginate %>

<ul class="users">
  <% @hospitals.each do |hospital| %>
    <li>
      <%= gravatar_for hospital, size: 52 %>
      <%= link_to hospital.hospital_name, hospital %>
      
  
    </li>
  <% end %>
</ul>

<%= will_paginate %>

app/views/hospitals/new.html.erb
<h1>Hospitals#new</h1>
<p>Find me in app/views/hospitals/new.html.erb</p>

app/views/hospitals/show.html.erb
<h1>Hospitals#show</h1>
<p>Find me in app/views/hospitals/show.html.erb</p>
<%= render 'shared/blood_form'%>

app/views/hospitals/update.html.erb
<h1>Hospitals#update</h1>
<p>Find me in app/views/hospitals/update.html.erb</p>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to "Gread",   root_path %>
    by <a href="https://www.facebook.com/devangtgr8">Devang Gupta</a>
     and <a href="https://www.facebook.com/shivamsatija04">Shivam Satija</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Help", help_path %></li>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="#">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Thunderbolt", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim'%>
 
</head>
<body>
	<div>
		<% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      	<% end %>
		<%= render 'layouts/header' %>
	
		<div class="container">

			<%= yield %>

		</div>

		<%= render 'layouts/footer' %>

		<%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>

app/views/shared/_blood_form.html.erb
<%= form_for(@hospital) do |f| %>

  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_field :donor, placeholder: "Donor Name" %>
    <%= f.select :type, ["A+","A-","B+","B-","AB+","AB-","O+","O-"] %>
    <%= f.text_field :reciever, placeholder: "Reciever Name" %>
  </div>
  
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
  </head>
  <body>
    <h1>About Us</h1>
    <p>
      
    </p>
  </body>
</html>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact Us') %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
  </head>
  <body>
    <h1>Contact Us</h1>
    <p>
      
    </p>
  </body>
</html>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
  </head>
  <body>
    <h1>Help</h1>
    <p>
      
    </p>
  </body>
</html>

app/views/static_pages/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
  </head>
  <body>

  

  	<div class="center hero-unit">
    	<h1>Thunderbolt</h1>
    	<h2>Donated organs and blood database</h2>
       
      <% if hospital_signed_in? %>
        Signed in as <%= current_hospital.email %>. Not you?
      <%= link_to "Sign out", destroy_hospital_session_path, :method => :delete %>
      
      <% else %>
      
      <%= link_to "Hospital Sign up", new_hospital_registration_path, class: "btn btn-large btn-primary" %>
      <% end %>
  
    	
    </div>

    
  </body>
</html>